#!/bin/sh
#PBS -l select=1:ncpus=16:mem=32gb
#PBS -l walltime=72:00:00
#PBS -k oe
module load intel-suite mpi fftw/3.3.3-double netcdf/4.4.4-fortran netcdf/4.4.1-c


cp $PBS_O_WORKDIR/install/* $TMPDIR
cp $PBS_O_WORKDIR/state.cdf.in $TMPDIR
cp $PBS_O_WORKDIR/GTD_lib.cdf $TMPDIR
cd $TMPDIR

mpiexec ./main.out

mkdir $HOME/runs/$PBS_JOBID
mkdir $HOME/runs/$PBS_JOBID/script

cp * $HOME/runs/$PBS_JOBID

cp $PBS_O_WORKDIR/program/* $HOME/runs/$PBS_JOBID/script/

exit 0
